export type NutritionalInformationType =
  | 'Acidification'
  | 'Ashes'
  | 'Calories'
  | 'Carbohydrates'
  | 'Cholesterol'
  | 'DietaryFiber'
  | 'Gi'
  | 'Gl'
  | 'MonounsaturatedFats'
  | 'PolyunsaturatedFats'
  | 'Proteins'
  | 'SaturedFats'
  | 'Sugar'
  | 'TotalFat';
