const commonWords = {
  ã: 'ã', // %C3%A3=
  ç: 'ç', // %C3%A7=
  á: 'á', // %C3%A1=
  ó: 'ó', // %C3%B3=
  é: 'é', // %C3%A9=
  í: 'í', // %C3%AD=
  â: 'â', // %C3%A2=
  ô: 'ô', // %C3%B4=
  ú: 'ú', // %C3%BA=
  chá: 'chá',
  fubá: 'fubá',
  café: 'café',
  grão: 'grão',
  óleo: 'óleo',
  água: 'água',
  grãos: 'grãos',
  feijão: 'feijão',
  rápido: 'rápido',
  tenção: 'tenção', // atenção
  rápida: 'rápida',
  açúcar: 'açúcar',
  prático: 'prático',
  'filé à': 'filé à',
  receita: 'receita',
  despeje: 'despeje',
  'uco de': 'uco de',
  prática: 'prática',
  farinha: 'farinha',
  orégano: 'orégano',
  amêndoa: 'amêndoa',
  ervilha: 'ervilha',
  lasanha: 'lasanha',
  torrado: 'torrado',
  porções: 'porções',
  torrada: 'torrada',
  antenha: 'antenha', // mantenha
  recheio: 'recheio',
  uniforme: 'uniforme',
  escasque: 'escasque', // descasque
  integral: 'integral',
  pimentão: 'pimentão',
  manteiga: 'manteiga',
  macarrão: 'macarrão',
  amendoim: 'amendoim',
  fricassê: 'fricassê',
  maracujá: 'maracujá',
  linguiça: 'linguiça',
  fermento: 'fermento',
  grelhado: 'grelhado',
  'olho de': 'olho de', // molho de
  sardinha: 'sardinha',
  triturar: 'triturar',
  barbecue: 'barbecue',
  refeição: 'refeição',
  saudável: 'saudável',
  'arne de': 'arne de', // carene de
  'a gosto': 'a gosto',
  'filé de': 'filé de',
  'sopa de': 'sopa de',
  'lata de': 'lata de',
  'pode de': 'pode de',
  'pavê de': 'pavê de',
  ransfira: 'ransfira', // transfira
  polvilhar: 'polvilhar',
  derretido: 'derretido',
  'ao forno': 'ao forno',
  almôndega: 'almôndega',
  batedeira: 'batedeira',
  sanduíche: 'sanduíche',
  crescente: 'crescente', // acrescente
  'leite de': 'leite de',
  gratinado: 'gratinado',
  beterraba: 'beterraba',
  'em tiras': 'em tiras',
  'fatia de': 'fatia de',
  temperado: 'temperado',
  'cerca de': 'cerca de',
  'olhas de': 'olhas de', // folhas de
  'isture a': 'isture a', // misture a
  'de molho': 'de molho',
  'torta de': 'torta de',
  'bolod de': 'bolod de',
  'em cubos': 'em cubos',
  'ao ponto': 'ao ponto',
  'aspas de': 'aspas de',
  'ique fino': 'ique fino', // pique fino
  'fogo alto': 'fogo alto',
  'alho poró': 'alho poró',
  'alho-poró': 'alho-poró',
  'coloque o': 'coloque o',
  'meia hora': 'meia hora',
  'em fatias': 'em fatias',
  microondas: 'microondas',
  '5 minutos': '5 minutos',
  frigideira: 'frigideira',
  'coloque a': 'coloque a',
  hambúrguer: 'hambúrguer',
  'emente de': 'emente de', // semente de
  'risoto de': 'risoto de',
  'mousse de': 'mousse de',
  '15 minutos': '15 minutos',
  'e preferir': 'e preferir', // se preferir
  'uma tigela': 'uma tigela', // em uma ou numa
  'farinha de': 'farinha de',
  '20 minutos': '20 minutos',
  'para baixo': 'para baixo',
  'empere com': 'empere com', // tempere com
  'unidade de': 'unidade de',
  ntiaderente: 'ntiaderente', // antiaderente
  'm terço de': 'm terço de',
  ingrediente: 'ingrediente',
  'm litro de': 'm litro de',
  '1 litro de': '1 litro de',
  '½ xícara de': '½ xícara de',
  'ave e seque': 'ave e seque', // lave e seque
  'sal a gosto': 'sal a gosto',
  desmanchando: 'desmanchando',
  '½ colher de': '½ colher de',
  'quanto isso': 'quanto isso', // enquanto isso
  '¼ xícara de': '¼ xícara de',
  '¼ colher de': '¼ colher de',
  'm quarto de': 'm quarto de',
  'refogado de': 'refogado de',
  'tomate seco': 'tomate seco',
  'rocesse por': 'rocesse por', // processe por
  'leite em pó': 'leite em pó',
  'carne moída': 'carne moída',
  'filé mignon': 'filé mignon',
  'milho verde': 'milho verde',
  'uma lata de': 'uma lata de',
  'um pacote de': 'um pacote de',
  'cozinhar até': 'cozinhar até',
  'baixe o fogo': 'baixe o fogo', // abaixe o fogo
  'papel toalha': 'papel toalha',
  'imenta preta': 'imenta preta',
  'imenta-preta': 'imenta-preta',
  'colher (chá)': 'colher (chá)',
  'ma xícara de': 'ma xícara de',
  'ma colher de': 'ma colher de',
  'ma porção de': 'ma porção de',
  'eio litro de': 'eio litro de',
  'água corrente': 'água corrente',
  'queijo ralado': 'queijo ralado',
  'leite de coco': 'leite de coco',
  'leite de soja': 'leite de soja',
  'tempero verde': 'tempero verde',
  'em uma panela': 'em uma panela',
  'pano de prato': 'pano de prato',
  'strogonoff de': 'strogonoff de',
  'pitada de sal': 'pitada de sal',
  'imentão verde': 'imentão verde',
  'eia xícara de': 'eia xícara de',
  '1/2 xícara de': '1/2 xícara de',
  'colher (sopa)': 'colher (sopa)',
  'dente de alho': 'dente de alho',
  'bem misturado': 'bem misturado',
  liquidificador: 'liquidificador',
  'olho de tomate': 'olho de tomate',
  'tempo de molho': 'tempo de molho',
  'dentes de alho': 'dentes de alho',
  'creme de leite': 'creme de leite',
  'zeite de oliva': 'zeite de oliva', // azeite de oliva
  'leite integral': 'leite integral',
  'azeitona preta': 'azeitona preta',
  'polvilho azedo': 'polvilho azedo',
  'imão siciliano': 'imão siciliano', // limão siciliano
  'picado em cubos': 'picado em cubos',
  'picada em cubos': 'picada em cubos',
  'limão siciliano': 'limão siciliano',
  'molho de tomate': 'molho de tomate',
  'legumes assados': 'legumes assados',
  'imenta-do-reino': 'imenta-do-reino',
  'imenta do reino': 'imenta do reino',
  'colheres (sopa)': 'colheres (sopa)',
  'arinha de trigo': 'arinha de trigo',
  'cozinha a massa': 'cozinha a massa',
  'imentão amarelo': 'imentão amarelo',
  'nquanto o forno': 'nquanto o forno', // enquanto o forno
  'empo de preparo': 'empo de preparo', // tempo de preparo
  'imentão vermelho': 'imentão vermelho',
  'duas colheres de': 'duas colheres de',
  'xícaras (chá) de': 'xícaras (chá) de',
  'rato tradicional': 'rato tradicional', // prato
  'leite condensado': 'leite condensado',
  'imenta calabresa': 'imenta calabresa', // pimenta calabresa
  'reaqueça o forno': 'reaqueça o forno', // preaqueça o forno
  'biscoito recheado': 'biscoito recheado',
  'limões silicianos': 'limões silicianos',
  'orre uma travessa': 'orre uma travessa', // forre uma travessa
  'uma tigela coloque ': 'uma tigela coloque ', // numa
  'bicarbonato de sódio': 'bicarbonato de sódio',
  'uma xícara de chá de': 'uma xícara de chá de',
  'chocolate meio amargo': 'chocolate meio amargo',
  'reaqueça o forno a 220 ºC': 'reaqueça o forno a 220 ºC',
};

const dictionaryKeys = Object.keys(commonWords);

export const commonDictionary = {
  _a_: dictionaryKeys[0],
  _b_: dictionaryKeys[1],
  _c_: dictionaryKeys[2],
  _d_: dictionaryKeys[3],
  _e_: dictionaryKeys[4],
  _f_: dictionaryKeys[5],
  _g_: dictionaryKeys[6],
  _h_: dictionaryKeys[7],
  _i_: dictionaryKeys[8],
  _j_: dictionaryKeys[9],
  _k_: dictionaryKeys[10],
  _l_: dictionaryKeys[11],
  _m_: dictionaryKeys[12],
  _n_: dictionaryKeys[13],
  _o_: dictionaryKeys[14],
  _p_: dictionaryKeys[15],
  _q_: dictionaryKeys[16],
  _r_: dictionaryKeys[17],
  _s_: dictionaryKeys[18],
  _t_: dictionaryKeys[19],
  _u_: dictionaryKeys[20],
  _v_: dictionaryKeys[21],
  _w_: dictionaryKeys[22],
  _x_: dictionaryKeys[23],
  _y_: dictionaryKeys[24],
  _z_: dictionaryKeys[25],
  _0_: dictionaryKeys[26],
  _1_: dictionaryKeys[27],
  _2_: dictionaryKeys[28],
  _3_: dictionaryKeys[29],
  _4_: dictionaryKeys[30],
  _5_: dictionaryKeys[31],
  _6_: dictionaryKeys[32],
  _7_: dictionaryKeys[33],
  _8_: dictionaryKeys[34],
  _9_: dictionaryKeys[35],

  '-a-': dictionaryKeys[36],
  '-b-': dictionaryKeys[37],
  '-c-': dictionaryKeys[38],
  '-d-': dictionaryKeys[39],
  '-e-': dictionaryKeys[40],
  '-f-': dictionaryKeys[41],
  '-g-': dictionaryKeys[42],
  '-h-': dictionaryKeys[43],
  '-i-': dictionaryKeys[44],
  '-j-': dictionaryKeys[45],
  '-k-': dictionaryKeys[46],
  '-l-': dictionaryKeys[47],
  '-m-': dictionaryKeys[48],
  '-n-': dictionaryKeys[49],
  '-o-': dictionaryKeys[50],
  '-p-': dictionaryKeys[51],
  '-q-': dictionaryKeys[52],
  '-r-': dictionaryKeys[53],
  '-s-': dictionaryKeys[54],
  '-t-': dictionaryKeys[55],
  '-u-': dictionaryKeys[56],
  '-v-': dictionaryKeys[57],
  '-w-': dictionaryKeys[58],
  '-x-': dictionaryKeys[59],
  '-y-': dictionaryKeys[60],
  '-z-': dictionaryKeys[61],
  '-0-': dictionaryKeys[62],
  '-1-': dictionaryKeys[63],
  '-2-': dictionaryKeys[64],
  '-3-': dictionaryKeys[65],
  '-4-': dictionaryKeys[66],
  '-5-': dictionaryKeys[67],
  '-6-': dictionaryKeys[68],
  '-7-': dictionaryKeys[69],
  '-8-': dictionaryKeys[70],
  '-9-': dictionaryKeys[71],

  '~a~': dictionaryKeys[72],
  '~b~': dictionaryKeys[73],
  '~c~': dictionaryKeys[74],
  '~d~': dictionaryKeys[75],
  '~e~': dictionaryKeys[76],
  '~f~': dictionaryKeys[77],
  '~g~': dictionaryKeys[78],
  '~h~': dictionaryKeys[79],
  '~i~': dictionaryKeys[80],
  '~j~': dictionaryKeys[81],
  '~k~': dictionaryKeys[82],
  '~l~': dictionaryKeys[83],
  '~m~': dictionaryKeys[84],
  '~n~': dictionaryKeys[85],
  '~o~': dictionaryKeys[86],
  '~p~': dictionaryKeys[87],
  '~q~': dictionaryKeys[88],
  '~r~': dictionaryKeys[89],
  '~s~': dictionaryKeys[90],
  '~t~': dictionaryKeys[91],
  '~u~': dictionaryKeys[92],
  '~v~': dictionaryKeys[93],
  '~w~': dictionaryKeys[94],
  '~x~': dictionaryKeys[95],
  '~y~': dictionaryKeys[96],
  '~z~': dictionaryKeys[97],
  '~0~': dictionaryKeys[98],
  '~1~': dictionaryKeys[99],
  '~2~': dictionaryKeys[100],
  '~3~': dictionaryKeys[101],
  '~4~': dictionaryKeys[102],
  '~5~': dictionaryKeys[103],
  '~6~': dictionaryKeys[104],
  '~7~': dictionaryKeys[105],
  '~8~': dictionaryKeys[106],
  '~9~': dictionaryKeys[107],

  _A_: dictionaryKeys[108],
  _B_: dictionaryKeys[109],
  _C_: dictionaryKeys[110],
  _D_: dictionaryKeys[111],
  _E_: dictionaryKeys[112],
  _F_: dictionaryKeys[113],
  _G_: dictionaryKeys[114],
  _H_: dictionaryKeys[115],
  _I_: dictionaryKeys[116],
  _J_: dictionaryKeys[117],
  _K_: dictionaryKeys[118],
  _L_: dictionaryKeys[119],
  _M_: dictionaryKeys[120],
  _N_: dictionaryKeys[121],
  _O_: dictionaryKeys[122],
  _P_: dictionaryKeys[123],
  _Q_: dictionaryKeys[124],
  _R_: dictionaryKeys[125],
  _S_: dictionaryKeys[126],
  _T_: dictionaryKeys[127],
  _U_: dictionaryKeys[128],
  _V_: dictionaryKeys[129],
  _W_: dictionaryKeys[130],
  _X_: dictionaryKeys[131],
  _Y_: dictionaryKeys[132],
  _Z_: dictionaryKeys[133],

  '-A-': dictionaryKeys[134],
  '-B-': dictionaryKeys[135],
  '-C-': dictionaryKeys[136],
  '-D-': dictionaryKeys[137],
  '-E-': dictionaryKeys[138],
  '-F-': dictionaryKeys[139],
  '-G-': dictionaryKeys[140],
  '-H-': dictionaryKeys[141],
  '-I-': dictionaryKeys[142],
  '-J-': dictionaryKeys[143],
  '-K-': dictionaryKeys[144],
  '-L-': dictionaryKeys[145],
  '-M-': dictionaryKeys[146],
  '-N-': dictionaryKeys[147],
  '-O-': dictionaryKeys[148],
  '-P-': dictionaryKeys[149],
  '-Q-': dictionaryKeys[150],
  '-R-': dictionaryKeys[151],
  '-S-': dictionaryKeys[152],
  '-U-': dictionaryKeys[153],
  '-V-': dictionaryKeys[154],
  '-W-': dictionaryKeys[155],
  '-X-': dictionaryKeys[156],
  '-Y-': dictionaryKeys[157],
  '-Z-': dictionaryKeys[158],

  '~A~': dictionaryKeys[159],
  '~B~': dictionaryKeys[160],
  '~C~': dictionaryKeys[161],
  '~D~': dictionaryKeys[162],
  '~E~': dictionaryKeys[163],
  '~F~': dictionaryKeys[164],
  '~G~': dictionaryKeys[165],
  '~H~': dictionaryKeys[166],
  '~I~': dictionaryKeys[167],
  '~J~': dictionaryKeys[168],
  '~K~': dictionaryKeys[169],
  '~L~': dictionaryKeys[170],
  '~M~': dictionaryKeys[171],
  '~N~': dictionaryKeys[172],
  '~O~': dictionaryKeys[173],
  '~P~': dictionaryKeys[174],
  '~Q~': dictionaryKeys[175],
  '~R~': dictionaryKeys[176],
  '~S~': dictionaryKeys[177],
  '~T~': dictionaryKeys[178],
  '~U~': dictionaryKeys[179],

  _aa_: dictionaryKeys[180],
  _ab_: dictionaryKeys[181],
  _ac_: dictionaryKeys[182],
  _ad_: dictionaryKeys[183],
  _ae_: dictionaryKeys[184],
  _af_: dictionaryKeys[185],
  _ag_: dictionaryKeys[186],
  _ah_: dictionaryKeys[187],
  _ai_: dictionaryKeys[188],
  _aj_: dictionaryKeys[189],
  _ak_: dictionaryKeys[190],
  _al_: dictionaryKeys[191],
  _am_: dictionaryKeys[192],
  _an_: dictionaryKeys[193],
  _ao_: dictionaryKeys[194],
  _ap_: dictionaryKeys[195],
  _aq_: dictionaryKeys[196],
  _ar_: dictionaryKeys[197],
  _as_: dictionaryKeys[198],
  _at_: dictionaryKeys[199],
};
