import { Vitamins, VitaminsData } from './vitamin.constants';

export function format(data?: Partial<VitaminsData>): Vitamins {
  return {
    a: {
      key: 'a',
      dv: 900,
      name: 'Retinol',
      nick: 'A',
      quantity: data?.a ?? 0,
      unity: 'μg',
    },
    c: {
      key: 'c',
      dv: 90,
      name: 'Ácido ascórbico',
      nick: 'C',
      quantity: data?.c ?? 0,
      unity: 'mg',
    },
    d: {
      key: 'd',
      dv: 600,
      name: 'Colecalciferol',
      nick: 'D',
      quantity: data?.d ?? 0,
      unity: 'UI',
    },
    e: {
      key: 'e',
      dv: 15,
      name: 'Tocoferol',
      nick: 'E',
      quantity: data?.e ?? 0,
      unity: 'mg',
    },
    k: {
      key: 'k',
      dv: 120,
      name: 'Filoquinona ou Fitomenadiona',
      nick: 'K',
      quantity: data?.k ?? 0,
      unity: 'μg',
    },
    b6: {
      key: 'b6',
      dv: 1.3,
      name: 'Piridoxina',
      nick: 'B6',
      quantity: data?.b6 ?? 0,
      unity: 'mg',
    },
    b11: {
      key: 'b11',
      dv: 0,
      name: 'Ácido pteroilheptaglutâmico',
      nick: 'B11',
      quantity: data?.b11 ?? 0,
      unity: 'mg',
    },
    b12: {
      key: 'b12',
      dv: 2.4,
      name: 'Cobalamina',
      nick: 'B12',
      quantity: data?.b12 ?? 0,
      unity: 'μg',
    },
    alphaCarotene: {
      key: 'alphaCarotene',
      dv: 0,
      name: 'Alfa-caroteno',
      nick: 'Alfa caroteno',
      quantity: data?.alphaCarotene ?? 0,
      unity: 'μg',
    },
    b1: {
      key: 'b1',
      dv: 0,
      name: 'Tiamina',
      nick: 'B1',
      quantity: data?.b1 ?? 0,
      unity: 'mg',
    },
    b2: {
      key: 'b2',
      dv: 0,
      name: 'Riboflavina',
      nick: 'B2',
      quantity: data?.b2 ?? 0,
      unity: 'mg',
    },
    b3: {
      key: 'b3',
      dv: 0,
      name: 'Niacina',
      nick: 'B3',
      quantity: data?.b3 ?? 0,
      unity: 'mg',
    },
    b5: {
      key: 'b5',
      dv: 0,
      name: 'Ácido pantotênico',
      nick: 'B5',
      quantity: data?.b5 ?? 0,
      unity: 'mg',
    },
    b7: {
      key: 'b7',
      dv: 0,
      name: 'Biotina',
      nick: 'B7',
      quantity: data?.b7 ?? 0,
      unity: 'mg',
    },
    b9: {
      key: 'b9',
      dv: 0,
      name: 'Ácido fólico ou folacina ou ácido pteroil-L-glutâmico ou folato',
      nick: 'B9',
      quantity: data?.b9 ?? 0,
      unity: 'μg',
    },
    betaCarotene: {
      key: 'betaCarotene',
      dv: 0,
      name: 'Betacaroteno',
      nick: 'Betacaroteno',
      quantity: data?.betaCarotene ?? 0,
      unity: 'μg',
    },
    choline: {
      key: 'choline',
      dv: 0,
      name: 'Colina',
      nick: 'Colina',
      quantity: data?.choline ?? 0,
      unity: 'mg',
    },
    cryptoxanthinCarotene: {
      key: 'cryptoxanthinCarotene',
      dv: 0,
      name: 'Criptoxantina',
      nick: 'Criptoxantina',
      quantity: data?.cryptoxanthinCarotene ?? 0,
      unity: 'μg',
    },
    d2: {
      key: 'd2',
      dv: 0,
      name: 'Ergocalciferol',
      nick: 'D₂',
      quantity: data?.d2 ?? 0,
      unity: 'μg',
    },
    d3: {
      key: 'd3',
      dv: 2000,
      name: 'Colecalciferol',
      nick: 'D₃',
      quantity: data?.d3 ?? 0,
      unity: 'μg',
    },
    lycopene: {
      key: 'lycopene',
      dv: 0,
      name: 'Licopeno',
      nick: 'Licopeno',
      quantity: data?.lycopene ?? 0,
      unity: 'μg',
    },
  };
}
