--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: RecipeStep; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."RecipeStep" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Ingredients" text NOT NULL,
    "Preparation" text NOT NULL,
    "Additional" text NOT NULL,
    "Recipeid" integer
);


ALTER TABLE public."RecipeStep" OWNER TO admin;

--
-- Name: RecipeStep_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."RecipeStep" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RecipeStep_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.recipes (
    id integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Additional" text
);


ALTER TABLE public.recipes OWNER TO admin;

--
-- Name: recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: RecipeStep; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."RecipeStep" ("Id", "Name", "Ingredients", "Preparation", "Additional", "Recipeid") FROM stdin;
\.


--
-- Data for Name: recipes; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.recipes (id, "Name", "Description", "Additional") FROM stdin;
\.


--
-- Name: RecipeStep_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."RecipeStep_Id_seq"', 1, false);


--
-- Name: recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.recipes_id_seq', 1, false);


--
-- Name: RecipeStep PK_RecipeStep; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RecipeStep"
    ADD CONSTRAINT "PK_RecipeStep" PRIMARY KEY ("Id");


--
-- Name: recipes PK_recipes; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.recipes
    ADD CONSTRAINT "PK_recipes" PRIMARY KEY (id);


--
-- Name: IX_RecipeStep_Recipeid; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_RecipeStep_Recipeid" ON public."RecipeStep" USING btree ("Recipeid");


--
-- Name: RecipeStep FK_RecipeStep_recipes_Recipeid; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RecipeStep"
    ADD CONSTRAINT "FK_RecipeStep_recipes_Recipeid" FOREIGN KEY ("Recipeid") REFERENCES public.recipes(id);


--
-- PostgreSQL database dump complete
--

