import { Minerals, MineralsData } from './mineral.constants';

export function format(data?: Partial<MineralsData>): Minerals {
  return {
    calcium: {
      dv: 1000,
      key: 'calcium',
      name: 'Cálcio',
      nick: 'Ca',
      quantity: data?.calcium ?? 0,
      unity: 'mg',
    },
    copper: {
      dv: 2.7,
      key: 'copper',
      name: 'Cobre',
      nick: 'Cu',
      quantity: data?.copper ?? 0,
      unity: 'mg',
    },
    fluoride: {
      dv: 0,
      key: 'fluoride',
      name: 'Flúor',
      nick: 'F',
      quantity: data?.fluoride || 0,
      unity: 'μg',
    },
    iron: {
      dv: 10,
      key: 'iron',
      name: 'Ferro',
      nick: 'Fe',
      quantity: data?.iron ?? 0,
      unity: 'mg',
    },
    magnesium: {
      dv: 0,
      key: 'magnesium',
      name: 'Magnésio',
      nick: 'Mg',
      quantity: data?.magnesium ?? 0,
      unity: 'mg',
    },
    manganese: {
      dv: 0,
      key: 'manganese',
      name: 'Manganês',
      nick: 'Mn',
      quantity: data?.manganese ?? 0,
      unity: 'mg',
    },
    phosphorus: {
      dv: 0,
      key: 'phosphorus',
      name: 'Fósforo',
      nick: 'P',
      quantity: data?.phosphorus || 0,
      unity: 'mg',
    },
    potassium: {
      dv: 0,
      key: 'potassium',
      name: 'Potássio',
      nick: 'K',
      quantity: data?.potassium ?? 0,
      unity: 'mg',
    },
    sodium: {
      dv: 0,
      key: 'sodium',
      name: 'Sódio',
      nick: 'Na',
      quantity: data?.sodium ?? 0,
      unity: 'mg',
    },
    zinc: {
      dv: 0,
      key: 'zinc',
      name: 'Zinco',
      nick: 'Zn',
      quantity: data?.zinc ?? 0,
      unity: 'mg',
    },
    selenium: {
      dv: 0,
      key: 'selenium',
      name: 'Selênio',
      nick: 'Se',
      quantity: data?.selenium ?? 0,
      unity: 'mcg',
    },
  };
}
