version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: caderninho-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: caderninho
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
