import type { Metadata } from 'next';
import Script from 'next/script';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import '@fontsource/dosis';
import '@fontsource/cinzel';
import '@fontsource/vibur';
import { LanguageProvider } from '../contexts/language';
import { ClientNavigationProvider } from '@/providers/client-navigation.provider';
import StickyHeaderInit from '@/components/sticky-header-init';
import { LoadingProvider } from '@/providers/loading';
import { DataProvider } from '@/providers/data';
import { CurrentRecipeProvider } from '@/providers/current-recipe';
import { NavigationProvider } from '@/providers/navigation.provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // App icons and manifest
  icons: {
    icon: '/logo.png',
    apple: '/logo.png',
    shortcut: '/logo.png',
  },
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {/* Google Identity Services for Sign-In */}
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="afterInteractive"
          async
        />
        {/* Initialize Ionicons custom element on the client */}{/* Initialize page-wide sticky header behavior on client */}
        <StickyHeaderInit />
        <NavigationProvider>
          <LoadingProvider>
            <DataProvider>
              <CurrentRecipeProvider>
                <LanguageProvider>{children}</LanguageProvider>
              </CurrentRecipeProvider>
            </DataProvider>
          </LoadingProvider>
        </NavigationProvider>
      </body>
    </html>
  );
}


