import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import '@fontsource/dosis';
import '@fontsource/cinzel';
import '@fontsource/vibur';
import { LanguageProvider } from '../contexts/language';
import IoniconsInit from '@/components/ionicons-init';
import { ClientNavigationProvider } from '@/providers/client-navigation.provider';
import StickyHeaderInit from '@/components/sticky-header-init';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {/* Initialize Ionicons custom element on the client */}
        <IoniconsInit />
        {/* Initialize page-wide sticky header behavior on client */}
        <StickyHeaderInit />
        <ClientNavigationProvider>
          <LanguageProvider>{children}</LanguageProvider>
        </ClientNavigationProvider>
      </body>
    </html>
  );
}
