// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223094539_FoodEditRequestAddIndexToStatus")]
    partial class FoodEditRequestAddIndexToStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.CategoryEditRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Status");

                    b.ToTable("CategoryEditRequest");
                });

            modelBuilder.Entity("Server.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AminoAcidsScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IconId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Imgs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("Server.Models.FoodEditRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId", "Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_FoodEditRequest_Pending")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("FoodEditRequest");
                });

            modelBuilder.Entity("Server.Models.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodIcon", (string)null);
                });

            modelBuilder.Entity("Server.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasColumnType("text");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Categories");

                    b.Property<int?>("CopiedFromRecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Imgs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LatestRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MergedIntoRecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("PublishedRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SavedByOthersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TombstoneStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LatestRevisionId");

                    b.HasIndex("MergedIntoRecipeId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublishedRevisionId");

                    b.HasIndex("Slug");

                    b.HasIndex("Visibility", "TombstoneStatus");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("Server.Models.RecipeCategoryOpen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("RecipeCategoryOpen");
                });

            modelBuilder.Entity("Server.Models.RecipeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name");

                    b.ToTable("RecipeList");
                });

            modelBuilder.Entity("Server.Models.RecipeListItem", b =>
                {
                    b.Property<int>("RecipeListId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("RecipeListId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeListItem");
                });

            modelBuilder.Entity("Server.Models.RecipeRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedRecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "RelatedRecipeId")
                        .IsUnique();

                    b.ToTable("RecipeRelation");
                });

            modelBuilder.Entity("Server.Models.RecipeRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Keys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("ModerationNotes")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaseRevisionId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RecipeId", "Status");

                    b.ToTable("RecipeRevisions");
                });

            modelBuilder.Entity("Server.Models.RecipeShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("RecipeShare");
                });

            modelBuilder.Entity("Server.Models.UserProfile", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CulturalRestrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DietStyles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("FeaturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GivenName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Intolerances")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MedicalRestrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalPreferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("OwnerId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Server.Models.Food", b =>
                {
                    b.HasOne("Server.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Server.Models.AminoAcids", "AminoAcids", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Alanine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Arginine")
                                .HasColumnType("double precision");

                            b1.Property<double>("AsparticAcid")
                                .HasColumnType("double precision");

                            b1.Property<double>("Cystine")
                                .HasColumnType("double precision");

                            b1.Property<double>("GlutamicAcid")
                                .HasColumnType("double precision");

                            b1.Property<double>("Glutamine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Glycine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Histidine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Isoleucine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Leucine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Lysine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Methionine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Phenylalanine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Proline")
                                .HasColumnType("double precision");

                            b1.Property<double>("Serine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Threonine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Tryptophan")
                                .HasColumnType("double precision");

                            b1.Property<double>("Tyrosine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Valine")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.EssentialAminoAcids", "EssentialAminoAcids", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Histidine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Isoleucine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Leucine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Lysine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Methionine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Phenylalanine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Threonine")
                                .HasColumnType("double precision");

                            b1.Property<double>("Tryptophan")
                                .HasColumnType("double precision");

                            b1.Property<double>("Valine")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.LanguageText", "Description", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.LanguageText", "Keys", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.LanguageText", "Name", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.Measure", "Measures", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double?>("Breast")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Bunch")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Can")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Clove")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Cup")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Glass")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Pinch")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Slice")
                                .HasColumnType("double precision");

                            b1.Property<double?>("SmallCup")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Spoon")
                                .HasColumnType("double precision");

                            b1.Property<double?>("TeaSpoon")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Unity")
                                .HasColumnType("double precision");

                            b1.Property<double?>("UnityLarge")
                                .HasColumnType("double precision");

                            b1.Property<double?>("UnitySmall")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.Minerals", "Minerals", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calcium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Copper")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fluoride")
                                .HasColumnType("double precision");

                            b1.Property<double>("Iron")
                                .HasColumnType("double precision");

                            b1.Property<double>("Magnesium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Manganese")
                                .HasColumnType("double precision");

                            b1.Property<double>("Phosphorus")
                                .HasColumnType("double precision");

                            b1.Property<double>("Potassium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Selenium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sodium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Zinc")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.NutritionalInformation", "NutritionalInformation", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("Acidification")
                                .HasColumnType("double precision");

                            b1.Property<double>("Ashes")
                                .HasColumnType("double precision");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision");

                            b1.Property<double>("Carbohydrates")
                                .HasColumnType("double precision");

                            b1.Property<double>("Cholesterol")
                                .HasColumnType("double precision");

                            b1.Property<double>("DietaryFiber")
                                .HasColumnType("double precision");

                            b1.Property<double>("Gi")
                                .HasColumnType("double precision");

                            b1.Property<double>("Gl")
                                .HasColumnType("double precision");

                            b1.Property<double>("MonounsaturatedFats")
                                .HasColumnType("double precision");

                            b1.Property<double>("PolyunsaturatedFats")
                                .HasColumnType("double precision");

                            b1.Property<double>("Proteins")
                                .HasColumnType("double precision");

                            b1.Property<double>("SaturedFats")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sugar")
                                .HasColumnType("double precision");

                            b1.Property<double>("TotalFat")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.OwnsOne("Server.Models.Vitamins", "Vitamins", b1 =>
                        {
                            b1.Property<int>("FoodId")
                                .HasColumnType("integer");

                            b1.Property<double>("A")
                                .HasColumnType("double precision");

                            b1.Property<double>("AlphaCarotene")
                                .HasColumnType("double precision");

                            b1.Property<double>("B1")
                                .HasColumnType("double precision");

                            b1.Property<double>("B11")
                                .HasColumnType("double precision");

                            b1.Property<double>("B12")
                                .HasColumnType("double precision");

                            b1.Property<double>("B2")
                                .HasColumnType("double precision");

                            b1.Property<double>("B3")
                                .HasColumnType("double precision");

                            b1.Property<double>("B5")
                                .HasColumnType("double precision");

                            b1.Property<double>("B6")
                                .HasColumnType("double precision");

                            b1.Property<double>("B7")
                                .HasColumnType("double precision");

                            b1.Property<double>("B9")
                                .HasColumnType("double precision");

                            b1.Property<double>("BetaCarotene")
                                .HasColumnType("double precision");

                            b1.Property<double>("C")
                                .HasColumnType("double precision");

                            b1.Property<double>("Choline")
                                .HasColumnType("double precision");

                            b1.Property<double>("CryptoxanthinCarotene")
                                .HasColumnType("double precision");

                            b1.Property<double>("D")
                                .HasColumnType("double precision");

                            b1.Property<double>("D2")
                                .HasColumnType("double precision");

                            b1.Property<double>("D3")
                                .HasColumnType("double precision");

                            b1.Property<double>("E")
                                .HasColumnType("double precision");

                            b1.Property<double>("K")
                                .HasColumnType("double precision");

                            b1.Property<double>("Lycopene")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodId");

                            b1.ToTable("Food");

                            b1.WithOwner()
                                .HasForeignKey("FoodId");
                        });

                    b.Navigation("AminoAcids")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("EssentialAminoAcids")
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Keys")
                        .IsRequired();

                    b.Navigation("Measures")
                        .IsRequired();

                    b.Navigation("Minerals")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("NutritionalInformation")
                        .IsRequired();

                    b.Navigation("Vitamins")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Icon", b =>
                {
                    b.OwnsOne("Server.Models.LanguageText", "Keys", b1 =>
                        {
                            b1.Property<int>("IconId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IconId");

                            b1.ToTable("FoodIcon");

                            b1.WithOwner()
                                .HasForeignKey("IconId");
                        });

                    b.OwnsOne("Server.Models.LanguageText", "Name", b1 =>
                        {
                            b1.Property<int>("IconId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IconId");

                            b1.HasIndex("En")
                                .IsUnique();

                            b1.ToTable("FoodIcon");

                            b1.WithOwner()
                                .HasForeignKey("IconId");
                        });

                    b.Navigation("Keys")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Recipe", b =>
                {
                    b.HasOne("Server.Models.RecipeRevision", "LatestRevision")
                        .WithMany()
                        .HasForeignKey("LatestRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Recipe", "MergedIntoRecipe")
                        .WithMany()
                        .HasForeignKey("MergedIntoRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.UserProfile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.RecipeRevision", "PublishedRevision")
                        .WithMany()
                        .HasForeignKey("PublishedRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LatestRevision");

                    b.Navigation("MergedIntoRecipe");

                    b.Navigation("Owner");

                    b.Navigation("PublishedRevision");
                });

            modelBuilder.Entity("Server.Models.RecipeCategoryOpen", b =>
                {
                    b.OwnsOne("Server.Models.LanguageText", "Description", b1 =>
                        {
                            b1.Property<int>("RecipeCategoryOpenId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RecipeCategoryOpenId");

                            b1.ToTable("RecipeCategoryOpen");

                            b1.WithOwner()
                                .HasForeignKey("RecipeCategoryOpenId");
                        });

                    b.OwnsOne("Server.Models.LanguageText", "Name", b1 =>
                        {
                            b1.Property<int>("RecipeCategoryOpenId")
                                .HasColumnType("integer");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Pt")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RecipeCategoryOpenId");

                            b1.ToTable("RecipeCategoryOpen");

                            b1.WithOwner()
                                .HasForeignKey("RecipeCategoryOpenId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.RecipeListItem", b =>
                {
                    b.HasOne("Server.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.RecipeList", "RecipeList")
                        .WithMany("Items")
                        .HasForeignKey("RecipeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RecipeList");
                });

            modelBuilder.Entity("Server.Models.RecipeRevision", b =>
                {
                    b.HasOne("Server.Models.RecipeRevision", "BaseRevision")
                        .WithMany()
                        .HasForeignKey("BaseRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Recipe", "Recipe")
                        .WithMany("Revisions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Server.Models.RecipeRevisionStep", "Steps", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Additional")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IngredientsText")
                                .HasColumnType("text");

                            b1.Property<string>("Preparation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("RecipeRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeRevisionId");

                            b1.ToTable("RecipeRevisionStep");

                            b1.WithOwner()
                                .HasForeignKey("RecipeRevisionId");

                            b1.OwnsMany("Server.Models.RecipeRevisionIngredient", "Ingredients", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("FoodId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("MeasureQuantity")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("MeasureType")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Quantity")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FoodId");

                                    b2.HasIndex("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionIngredient");

                                    b2.HasOne("Server.Models.Food", "Food")
                                        .WithMany()
                                        .HasForeignKey("FoodId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");

                                    b2.OwnsOne("Server.Shared.AminoAcidsBase", "AminoAcids", b3 =>
                                        {
                                            b3.Property<int>("RecipeRevisionIngredientId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Alanine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Arginine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("AsparticAcid")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Cystine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("GlutamicAcid")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Glutamine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Glycine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Histidine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Isoleucine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Leucine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Lysine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Methionine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Phenylalanine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Proline")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Serine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Threonine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Tryptophan")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Tyrosine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Valine")
                                                .HasColumnType("double precision");

                                            b3.HasKey("RecipeRevisionIngredientId");

                                            b3.ToTable("RecipeRevisionIngredient");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipeRevisionIngredientId");
                                        });

                                    b2.OwnsOne("Server.Shared.EssentialAminoAcidsBase", "EssentialAminoAcids", b3 =>
                                        {
                                            b3.Property<int>("RecipeRevisionIngredientId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Histidine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Isoleucine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Leucine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Lysine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Methionine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Phenylalanine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Threonine")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Tryptophan")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Valine")
                                                .HasColumnType("double precision");

                                            b3.HasKey("RecipeRevisionIngredientId");

                                            b3.ToTable("RecipeRevisionIngredient");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipeRevisionIngredientId");
                                        });

                                    b2.OwnsOne("Server.Shared.MineralsBase", "Minerals", b3 =>
                                        {
                                            b3.Property<int>("RecipeRevisionIngredientId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Calcium")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Copper")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Fluoride")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Iron")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Magnesium")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Manganese")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Phosphorus")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Potassium")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Selenium")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Sodium")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Zinc")
                                                .HasColumnType("double precision");

                                            b3.HasKey("RecipeRevisionIngredientId");

                                            b3.ToTable("RecipeRevisionIngredient");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipeRevisionIngredientId");
                                        });

                                    b2.OwnsOne("Server.Shared.NutritionalInformationBase", "NutritionalInformation", b3 =>
                                        {
                                            b3.Property<int>("RecipeRevisionIngredientId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Acidification")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Ashes")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Calories")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Carbohydrates")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Cholesterol")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("DietaryFiber")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Gi")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Gl")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("MonounsaturatedFats")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("PolyunsaturatedFats")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Proteins")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("SaturedFats")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Sugar")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("TotalFat")
                                                .HasColumnType("double precision");

                                            b3.HasKey("RecipeRevisionIngredientId");

                                            b3.ToTable("RecipeRevisionIngredient");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipeRevisionIngredientId");
                                        });

                                    b2.OwnsOne("Server.Shared.VitaminsBase", "Vitamins", b3 =>
                                        {
                                            b3.Property<int>("RecipeRevisionIngredientId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("A")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("AlphaCarotene")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B1")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B11")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B12")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B2")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B3")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B5")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B6")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B7")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("B9")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("BetaCarotene")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("C")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Choline")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("CryptoxanthinCarotene")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("D")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("D2")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("D3")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("E")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("K")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Lycopene")
                                                .HasColumnType("double precision");

                                            b3.HasKey("RecipeRevisionIngredientId");

                                            b3.ToTable("RecipeRevisionIngredient");

                                            b3.WithOwner()
                                                .HasForeignKey("RecipeRevisionIngredientId");
                                        });

                                    b2.Navigation("AminoAcids")
                                        .IsRequired();

                                    b2.Navigation("EssentialAminoAcids")
                                        .IsRequired();

                                    b2.Navigation("Food");

                                    b2.Navigation("Minerals")
                                        .IsRequired();

                                    b2.Navigation("NutritionalInformation")
                                        .IsRequired();

                                    b2.Navigation("Vitamins")
                                        .IsRequired();
                                });

                            b1.OwnsOne("Server.Shared.AminoAcidsBase", "AminoAcids", b2 =>
                                {
                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Alanine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Arginine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("AsparticAcid")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Cystine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("GlutamicAcid")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Glutamine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Glycine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Histidine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Isoleucine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Leucine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lysine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Methionine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Phenylalanine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Proline")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Serine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Threonine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Tryptophan")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Tyrosine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Valine")
                                        .HasColumnType("double precision");

                                    b2.HasKey("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionStep");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");
                                });

                            b1.OwnsOne("Server.Shared.EssentialAminoAcidsBase", "EssentialAminoAcids", b2 =>
                                {
                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Histidine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Isoleucine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Leucine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lysine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Methionine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Phenylalanine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Threonine")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Tryptophan")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Valine")
                                        .HasColumnType("double precision");

                                    b2.HasKey("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionStep");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");
                                });

                            b1.OwnsOne("Server.Shared.MineralsBase", "Minerals", b2 =>
                                {
                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Calcium")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Copper")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Fluoride")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Iron")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Magnesium")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Manganese")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Phosphorus")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Potassium")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Selenium")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Sodium")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Zinc")
                                        .HasColumnType("double precision");

                                    b2.HasKey("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionStep");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");
                                });

                            b1.OwnsOne("Server.Shared.NutritionalInformationBase", "NutritionalInformation", b2 =>
                                {
                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Acidification")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Ashes")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Calories")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Carbohydrates")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Cholesterol")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("DietaryFiber")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Gi")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Gl")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("MonounsaturatedFats")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("PolyunsaturatedFats")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Proteins")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("SaturedFats")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Sugar")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("TotalFat")
                                        .HasColumnType("double precision");

                                    b2.HasKey("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionStep");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");
                                });

                            b1.OwnsOne("Server.Shared.VitaminsBase", "Vitamins", b2 =>
                                {
                                    b2.Property<int>("RecipeRevisionStepId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("A")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("AlphaCarotene")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B1")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B11")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B12")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B2")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B3")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B5")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B6")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B7")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("B9")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("BetaCarotene")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("C")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Choline")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("CryptoxanthinCarotene")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("D")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("D2")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("D3")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("E")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("K")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Lycopene")
                                        .HasColumnType("double precision");

                                    b2.HasKey("RecipeRevisionStepId");

                                    b2.ToTable("RecipeRevisionStep");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeRevisionStepId");
                                });

                            b1.Navigation("AminoAcids")
                                .IsRequired();

                            b1.Navigation("EssentialAminoAcids")
                                .IsRequired();

                            b1.Navigation("Ingredients");

                            b1.Navigation("Minerals")
                                .IsRequired();

                            b1.Navigation("NutritionalInformation")
                                .IsRequired();

                            b1.Navigation("Vitamins")
                                .IsRequired();
                        });

                    b.Navigation("BaseRevision");

                    b.Navigation("Recipe");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Server.Models.Recipe", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Server.Models.RecipeList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
